# Grafana数据源配置
# 配置Prometheus作为Grafana的数据源

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"
    version: 1

  - name: Prometheus-Alertmanager
    type: prometheus
    access: proxy
    url: http://alertmanager:9093
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "30s"
    version: 1